const summaries = ["When I was 21, I climbed Mount Everest. Not metaphorically—I literally climbed the highest mountain on Earth. While I was hiking, I thought about quitting approximately 5,000 times. (And that’s a lowball estimate.) But despite the high winds, low altitude, mental and physical fatigue, and trail mix overdose, I kept going. I’m that person. Once I say I’ll do something, it will happen. Now, I put that perseverance to work as a senior account manager for Polar. I don’t have to climb any mountains…but I do have to move them. I’m well-versed in negotiations, planning and development, relationship management, operations, and logistics coordination and scheduling. If you’re interested in grabbing coffee and talking shop (or to hear how I almost fell off the mountain at 27K feet), please send an email my way.",

"I have over 15 years of experience working in data science. Currently, I work as Asana’s Senior Data Manager, improving products and services for our customers by using advanced analytics, standing up big-data analytical tools, creating and maintaining models, and onboarding compelling new data sets. Previously, I was the Chief Data Scientist at Guru, where I analyzed data from some of the biggest enterprise and networks in the world to educate the market on long-term internet trends. Competencies: data science, machine learning, cloud computing, Hadoop, Python/Java/R, network protocols.",

"I’m a talent acquisition specialist with an interest in building the most effective workforces possible. For over 20 years, I’ve been helping businesses find their perfect hires. I also do consulting on compensation and benefits, new hire processes, and company culture. When I’m not on the job, I love hiking with my dog, working my way through every recipe in the family cookbook, and indulging my love for seeing new places.If you’d like to learn more about how my services can help your company, please reach out via email (janedoe@gmail.com).",

"I’m a freelance multi-disciplinary graphic designer who’s delivered creative and engaging solutions across brand identity, print, packaging, and digital media. In 2013, my online brand campaign for the Dorsey Children’s Hospital won a GDUSA award, one of the most prestigious honors in the graphic design industry. My work has also been featured in Creatique Bloq, Compound Magazine, and on the Creative Review blog. Skills: logo design, web design, branding and identity, typography, UI design, packaging, CSS, HTML, InDesign, Photoshop, Illustrator. If you have a project I can help with, please get in touch.",

"Transitioning from IT to Digital Marketing & Career Advancement was one of the toughest transitions of my life.I went through a life crisis trying it figure it all out. Going through a life and identity crisis while your bank account also depends on the answer is something I hope you never have to go through. I went from being an expert in “IT Consulting” with 9 years experience to becoming a “Marketing Director” and “Career Advancement Expert” within 2 years.",

"I wrote the book conservatively titled, 'Fire Me I Beg You.' LinkedIn chose one of my posts as one of the best articles in 2014. My articles have accumulated over 3 million views with 4 posts over 400,000 views. I built a strong professional network in Chicago with growing startups, investors, and successful entrepreneurs by taking 250 coffee meetings in 400 days. The CEO of Deloitte Consulting loved my resignation letter so much that he sent it to the entire company. My writing has been featured in the New York Times, Business Insider, Forbes, CBS News and Lifehacker. I stalked James Altucher for 4 years. The result? He invited me to participate in his award winning podcast.",

"For the past seven years I have been working as an editor in the publishing industry, conceiving and creating bold, original content for both print and web properties and interacting with the entertainment, fashion, literary, and public relations communities. I am now exploring new career options and I believe I am uniquely qualified for this position. My diverse practical experience, willingness to learn, and strong work ethic are just a few of my many strengths, and if given the opportunity, I would love to explain a little bit more about the professional and personal assets I would bring to the position."]

module.exports = {summaries}
